### ISSUE TITLE
How do I make all 404s be logged to elmah ?

### ISSUE THREAD

**Issue by yrshaikh** [andrewdavey/NotFoundMvc#23]
I have been using NotFoundMvc in few of my projects. Also along with this I use Elmah for error hanlding. All 404 are handled by NotFoundMvc, what change do I have to make so that all 404 errors are logged to elmah ?

**Comment by DavidDeSloovere** [comment]
Consolidating these logging issues into https://github.com/andrewdavey/NotFoundMvc/issues/30
