### ISSUE TITLE
Change web.config transform to only change the attribute of httpruntime

### ISSUE THREAD

**Issue by DavidDeSloovere** [andrewdavey/NotFoundMvc#26]
xdt:Transform="SetAttributes"

**Comment by Gavin-Paolucci-Kleinow** [comment]
I had a problem with this also. I had an existing httpErrors section in my web.config and the NotFoundMvc NuGet package added a second httpErrors section instead of modifying the existing one.

**Comment by DavidDeSloovere** [comment]
If the httpRuntime node isn't present, then xdt:Transform="SetAttributes" won't add it. 
So that would results in 0 or 1 httpRuntime node, while the current implementation results in 1 or 2 httpRuntime nodes.

**Comment by DavidDeSloovere** [comment]
Should be fixed with https://github.com/andrewdavey/NotFoundMvc/commit/7c5dba559511b2ed6afb554ed6a51439c621fa9a
