### ISSUE TITLE
attribute routing throws exception

### ISSUE THREAD

**Issue by joriszwart** [andrewdavey/NotFoundMvc#27]
When enabling attribute routing an exception is thrown.

For details see techvice/ErrorHandlerMVC#2 (same issue)

**Comment by joriszwart** [comment]
Apparently it is fixed in techvice/ErrorHandlerMvc@3dc6690

**Comment by devlife** [comment]
I'm still getting this exception. Any updates?

**Comment by DavidDeSloovere** [comment]
Nope. The original creator (Andrew Davey) is not on this project anymore. I just got access so it wouldn't be completely dead. 
If someone wants to fix this (and any other issues) I can merge and update the package on nuget (with myget in between)

**Comment by joriszwart** [comment]
There is a fix available: techvice/ErrorHandlerMvc@3dc6690

**Comment by DavidDeSloovere** [comment]
I'm not a git(hub) expert. Is there a way to get that commit in here as a PR?

**Comment by joriszwart** [comment]
Not automated I guess. The structure of *ErrorHandlerMvc* differs from *NotFoundMvc*. A part of the fix was done in `InternalErrorController` which is not available in *NotFoundMvc*.

In fact *NotFoundMvc* has twice as much source files as *ErrorHandlerMvc* has.

IMHO in the end it would be better to merge both projects and deprecate one of them.

@techvice: what do you think?

**Comment by techvice** [comment]
There is a way to merge the two different source paths together. @DavidDeSloovere I can walk you through it but development on my forked version has come to a halt. I just have been too occupied to address open issues and there are issues.

My fork basically built on the original and added internal error handling as well. At this point, it may be easier to make David a contributor on my fork and go from there. Just a suggestion.

**Comment by DavidDeSloovere** [comment]
You've got open issues, we've got open issues, everybody got issues ;-)
Let's try to resolve them I say!
Tell me what you need and we'll make it work.

**Comment by DavidDeSloovere** [comment]
@joriszwart or @devlife , if you guys want to try a CI build, I'm putting a pre-release on nuget in a few minutes.

**Comment by techvice** [comment]
@DavidDeSloovere I've added you as a collaborator to my project. Feel free to take it for a spin.

**Comment by Gavin-Paolucci-Kleinow** [comment]
I'm still having this issue using the [NotFound MVC 1.4.0-CI00006 package](https://www.nuget.org/packages/NotFoundMvc/1.4.0-CI00006). When will a version with this fix be published to NuGet?

**Comment by DavidDeSloovere** [comment]
It depends, how fast can you send a pull request? :-)
Can you post a repro?

**Comment by Gavin-Paolucci-Kleinow** [comment]
I guess I'm confused. What needs to be done still? I can try to give a hand.

**Comment by DavidDeSloovere** [comment]
I just commited a change that includes a "test" (not unit test) for attribute routing.
@Gavin-Paolucci-Kleinow, see if you can clone and try it out. It's in the SampleAppMvc5 project.

**Comment by Gavin-Paolucci-Kleinow** [comment]
SampleAppMvc5 works for me. It looks like the current master has fixed the problem. So now it's just publishing to NuGet?

**Comment by DavidDeSloovere** [comment]
I just pushed 1.4 to nuget. https://www.nuget.org/packages/NotFoundMvc/

**Comment by Gavin-Paolucci-Kleinow** [comment]
Thank you! I'm able to use Attribute routing in my project now!
